In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/hts_2024_basic_edition_csv.csv")

In [8]:
df.head(5)

,HTS Number,Indent,Description,Unit of Quantity,General Rate of Duty,Special Rate of Duty,Column 2 Rate of Duty,Quota Quantity,Additional Duties
0,0101,0,"Live horses, asses, mules and hinnies:",NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1,Horses:,NaN,NaN,NaN,NaN,NaN,NaN
2,0101.21.00,2,Purebred breeding animals,NaN,Free,NaN,Free,NaN,NaN
3,0101.21.00.10,3,Males,"[""No.""]",NaN,NaN,NaN,NaN,NaN
4,0101.21.00.20,3,Females,"[""No.""]",NaN,NaN,NaN,NaN,NaN

In [9]:
df.tail(5)

,HTS Number,Indent,Description,Unit of Quantity,General Rate of Duty,Special Rate of Duty,Column 2 Rate of Duty,Quota Quantity,Additional Duties
35739,9922.52.09,2,Goods of Mexico or goods of the United States ...,NaN,NaN,Free (S+),NaN,NaN,NaN
35740,9922.52.10,2,Goods of Canada provided for in note 2(b) to t...,NaN,NaN,1.3¢/kg (S+),NaN,NaN,NaN
35741,NaN,1,Goods provided for in subheading 5203.00.30:,NaN,NaN,NaN,NaN,NaN,NaN
35742,9922.52.11,2,Goods of Mexico or goods of the United States ...,NaN,NaN,Free (S+),NaN,NaN,NaN
35743,9922.52.12,2,Goods of Canada provided for in note 2(b) to t...,NaN,NaN,5.2¢/kg (S+),NaN,NaN,NaN

In [10]:
df.shape

(35744, 9)

In [12]:
df.columns

Index(['HTS Number', 'Indent', 'Description', 'Unit of Quantity',
       'General Rate of Duty', 'Special Rate of Duty', 'Column 2 Rate of Duty',
       'Quota Quantity', 'Additional Duties'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35744 entries, 0 to 35743
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   HTS Number             29743 non-null  object
 1   Indent                 35744 non-null  int64
 2   Description            35744 non-null  object
 3   Unit of Quantity       19664 non-null  object
 4   General Rate of Duty   13591 non-null  object
 5   Special Rate of Duty   9862 non-null   object
 6   Column 2 Rate of Duty  13249 non-null  object
 7   Quota Quantity         0 non-null      float64
 8   Additional Duties      512 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 2.5+ MB

In [17]:
'''
df.select_dtypes(include='object')
df.select_dtypes(include='int64')
'''
df.select_dtypes(include='float64')

       Quota Quantity
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
35739             NaN
35740             NaN
35741             NaN
35742             NaN
35743             NaN

[35744 rows x 1 columns]

In [20]:
df.describe()

             Indent  Quota Quantity
count  35744.000000             0.0
mean       2.990236             NaN
std        1.830030             NaN
min        0.000000             NaN
25%        2.000000             NaN
50%        3.000000             NaN
75%        4.000000             NaN
max       11.000000             NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35744 entries, 0 to 35743
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   HTS Number             29743 non-null  object
 1   Indent                 35744 non-null  int64
 2   Description            35744 non-null  object
 3   Unit of Quantity       19664 non-null  object
 4   General Rate of Duty   13591 non-null  object
 5   Special Rate of Duty   9862 non-null   object
 6   Column 2 Rate of Duty  13249 non-null  object
 7   Quota Quantity         0 non-null      float64
 8   Additional Duties      512 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 2.5+ MB

In [22]:
df.isnull().sum()

HTS Number                6001
Indent                       0
Description                  0
Unit of Quantity         16080
General Rate of Duty     22153
Special Rate of Duty     25882
Column 2 Rate of Duty    22495
Quota Quantity           35744
Additional Duties        35232
dtype: int64

In [28]:
df['Indent'].unique()
df['Indent'].value_counts()

Indent
3     7816
2     7204
4     6242
1     4362
5     3753
0     3222
6     1807
7      854
8      304
9      128
10      44
11       8
Name: count, dtype: int64

In [30]:
df['Description'].unique()

array(['Live horses, asses, mules and hinnies:', 'Horses:',
       'Purebred breeding animals', ...,
       'Goods provided for in subheading 5201.00.80:',
       'Goods provided for in subheading 5202.99.30:',
       'Goods provided for in subheading 5203.00.30:'], dtype=object)

In [32]:
df.Indent

0        0
1        1
2        2
3        3
4        3
        ..
35739    2
35740    2
35741    1
35742    2
35743    2
Name: Indent, Length: 35744, dtype: int64

In [34]:
df_indent0=df[df["Indent"]==0]
print(df_indent0)

      HTS Number  Indent                                        Description  \
0           0101       0             Live horses, asses, mules and hinnies:
12          0102       0                               Live bovine animals:
72          0103       0                                        Live swine:
83          0104       0                              Live sheep and goats:
86          0105       0  Live poultry of the following kinds: Chickens,...
...          ...     ...                                                ...
35616        NaN       0  Goods of Colombia, under the terms of U.S. not...
35619        NaN       0  Goods of Panama, under the terms of general no...
35674        NaN       0  Goods of Korea, under the terms of general not...
35704        NaN       0  Parts of air conditioning machines of heading ...
35707        NaN       0  Goods entered under the provisions of the US-M...

      Unit of Quantity General Rate of Duty Special Rate of Duty  \
0                  NaN                  NaN                  NaN
12                 NaN                  NaN                  NaN
72                 NaN                  NaN                  NaN
83                 NaN                  NaN                  NaN
86                 NaN                  NaN                  NaN
...                ...                  ...                  ...
35616              NaN                  NaN                  NaN
35619              NaN                  NaN                  NaN
35674              NaN                  NaN                  NaN
35704              NaN                  NaN                  NaN
35707              NaN                  NaN                  NaN

      Column 2 Rate of Duty  Quota Quantity Additional Duties
0                       NaN             NaN               NaN
12                      NaN             NaN               NaN
72                      NaN             NaN               NaN
83                      NaN             NaN               NaN
86                      NaN             NaN               NaN
...                     ...             ...               ...
35616                   NaN             NaN               NaN
35619                   NaN             NaN               NaN
35674                   NaN             NaN               NaN
35704                   NaN             NaN               NaN
35707                   NaN             NaN               NaN

[3222 rows x 9 columns]

In [36]:
df["Indent"] == 0

0         True
1        False
2        False
3        False
4        False
         ...
35739    False
35740    False
35741    False
35742    False
35743    False
Name: Indent, Length: 35744, dtype: bool

In [37]:
horses_rows = df[df["Description"].str.contains("Horses", na=False)]
print(horses_rows)

  HTS Number  Indent Description Unit of Quantity General Rate of Duty  \
1        NaN       1     Horses:              NaN                  NaN

  Special Rate of Duty Column 2 Rate of Duty  Quota Quantity Additional Duties
1                  NaN                   NaN             NaN               NaN